apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
data:
  username: YWx4c2VuZW4=
  password: Z2l0aHViX3BhdF8xMUFDMzNQWFEwWTFkS2dobzNHSEFzXzQzUEVWVTViaHFFbUlITVIzMlBDN0FNbVVOdVNUT1Jtc012dEEzeGtKczhTWFRTVENCWGE1V3llOXFr
