name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: |
        echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV; echo $GITHUB_ENV
        docker build . --file Dockerfile --tag alexcv:$GITHUB_ENV
    - name: Configuren Kubernetes Context
      env:
        KUBECONF: ${{secrets.KUBECONF}}
      run: mkdir ~/.kube; echo "$KUBECONF" > ~/.kube/config; kubectl get nodes
    - name: Adding alexcv repo
      run: |
        helm repo add alexcv https://charts.devsysop.com/
    - name: Getting repo list
      run: helm repo list