name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      env:
        GITHUB_REF_NAME: $GITHUB_REF_NAME
      run: docker build . --file Dockerfile --tag alexdevsysop/alexcv:$GITHUB_REF_NAME
    - name: Push the Docker image
      env:
        GITHUB_REF_NAME: $GITHUB_REF_NAME
      run: docker push alexdevsysop/alexcv:$GITHUB_REF_NAME
    - name: Configure Kubernetes Access
      env:
        KUBECONF: ${{secrets.KUBECONF}}
      run: mkdir ~/.kube; echo "$KUBECONF" > ~/.kube/config; kubectl get nodes
    - name: Adding alexcv repo
      run: |
        helm repo add alexcv https://charts.devsysop.com/
        helm repo update
    - name: Deploying alexcv helmchart
      env:
        GITHUB_REF_NAME: $GITHUB_REF_NAME
      run: helm upgrade --install alexcv alexcv/alexcv --set=image.tag=$GITHUB_REF_NAME