name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag alexcv:v28
    - name: Configuren Kubernetes Context
      env:
        KUBECONF: ${{secrets.KUBECONF}}
      run: echo "$KUBECONF" > kube.conf; kubectl config --kubeconfig="kube.conf"; rm -rf kube.conf; kubectl get nodes
    - name: Adding alexcv repo
      run: |
        helm repo add alexcv https://charts.devsysop.com/
    - name: Getting repo list
      run: helm repo list