name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo $GITHUB_REF_NAME; echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag alexcv:v28
    - name: Configuren Kubernetes Context
      env:
        KUBECONF: ${{secrets.KUBECONF}}
      run: mkdir ~/.kube; echo "$KUBECONF" > ~/.kube/config; kubectl get nodes
    - name: Adding alexcv repo
      run: |
        helm repo add alexcv https://charts.devsysop.com/
    - name: Getting repo list
      run: helm repo list